ALTER TABLE "Act" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'active';
ALTER TABLE "Act" ADD COLUMN "repealedById" INTEGER;
ALTER TABLE "Act" ADD CONSTRAINT "Act_repealedById_fkey" FOREIGN KEY ("repealedById") REFERENCES "Act"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "GazetteEntry" ADD COLUMN "revokedById" INTEGER;
ALTER TABLE "GazetteEntry" ADD CONSTRAINT "GazetteEntry_revokedById_fkey" FOREIGN KEY ("revokedById") REFERENCES "GazetteEntry"("id") ON DELETE SET NULL ON UPDATE CASCADE;
